<?php
require_once 'includes/config/database.php';

echo "=== Creating SHS Clearance Forms ===\n\n";

try {
    $pdo = Database::getInstance()->getConnection();
    
    // Get current active academic year and semester
    $stmt = $pdo->prepare("
        SELECT ay.academic_year_id, s.semester_id, ay.year as academic_year, s.semester_name
        FROM academic_years ay
        JOIN semesters s ON ay.academic_year_id = s.academic_year_id
        WHERE ay.is_active = 1 AND s.is_active = 1
        LIMIT 1
    ");
    $stmt->execute();
    $currentPeriod = $stmt->fetch(PDO::FETCH_ASSOC);
    
    if (!$currentPeriod) {
        echo "❌ No active academic year/semester found!\n";
        exit(1);
    }
    
    echo "📅 Current Period: {$currentPeriod['academic_year']} - {$currentPeriod['semester_name']}\n";
    echo "   Academic Year ID: {$currentPeriod['academic_year_id']}\n";
    echo "   Semester ID: {$currentPeriod['semester_id']}\n\n";
    
    // Get all SHS students who don't have clearance forms for this period
    $stmt = $pdo->prepare("
        SELECT s.user_id, s.student_id, u.first_name, u.last_name, s.sector
        FROM students s
        JOIN users u ON s.user_id = u.user_id
        WHERE s.sector = 'Senior High School'
        AND s.user_id NOT IN (
            SELECT cf.user_id 
            FROM clearance_forms cf 
            WHERE cf.academic_year_id = ? 
            AND cf.semester_id = ?
        )
        ORDER BY s.student_id
    ");
    $stmt->execute([$currentPeriod['academic_year_id'], $currentPeriod['semester_id']]);
    $shsStudents = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    echo "👥 Found " . count($shsStudents) . " SHS students without clearance forms:\n";
    foreach ($shsStudents as $student) {
        echo "   - {$student['student_id']}: {$student['first_name']} {$student['last_name']} (User ID: {$student['user_id']})\n";
    }
    echo "\n";
    
    if (empty($shsStudents)) {
        echo "✅ All SHS students already have clearance forms for this period!\n";
        exit(0);
    }
    
    // Create clearance forms for SHS students
    $createdForms = 0;
    $errors = [];
    
    foreach ($shsStudents as $student) {
        try {
            // Generate clearance form ID (will be auto-generated by trigger)
            $stmt = $pdo->prepare("
                INSERT INTO clearance_forms (
                    user_id, 
                    academic_year_id, 
                    semester_id, 
                    clearance_type, 
                    status
                ) VALUES (?, ?, ?, 'Senior High School', 'Unapplied')
            ");
            
            $stmt->execute([
                $student['user_id'],
                $currentPeriod['academic_year_id'],
                $currentPeriod['semester_id']
            ]);
            
            $createdForms++;
            echo "✅ Created form for {$student['student_id']}: {$student['first_name']} {$student['last_name']}\n";
            
        } catch (PDOException $e) {
            $errors[] = "Failed to create form for {$student['student_id']}: " . $e->getMessage();
            echo "❌ Error creating form for {$student['student_id']}: " . $e->getMessage() . "\n";
        }
    }
    
    echo "\n=== Summary ===\n";
    echo "📊 Forms Created: {$createdForms}\n";
    echo "❌ Errors: " . count($errors) . "\n";
    
    if (!empty($errors)) {
        echo "\nError Details:\n";
        foreach ($errors as $error) {
            echo "   - {$error}\n";
        }
    }
    
    // Verify the created forms
    echo "\n=== Verification ===\n";
    $stmt = $pdo->prepare("
        SELECT COUNT(*) as total_shs_forms
        FROM clearance_forms cf
        WHERE cf.clearance_type = 'Senior High School'
        AND cf.academic_year_id = ?
        AND cf.semester_id = ?
    ");
    $stmt->execute([$currentPeriod['academic_year_id'], $currentPeriod['semester_id']]);
    $result = $stmt->fetch(PDO::FETCH_ASSOC);
    
    echo "📋 Total SHS clearance forms for current period: {$result['total_shs_forms']}\n";
    
    // Show sample of created forms
    $stmt = $pdo->prepare("
        SELECT cf.clearance_form_id, cf.user_id, u.first_name, u.last_name, cf.clearance_type, cf.status
        FROM clearance_forms cf
        JOIN users u ON cf.user_id = u.user_id
        WHERE cf.clearance_type = 'Senior High School'
        AND cf.academic_year_id = ?
        AND cf.semester_id = ?
        ORDER BY cf.clearance_form_id
        LIMIT 5
    ");
    $stmt->execute([$currentPeriod['academic_year_id'], $currentPeriod['semester_id']]);
    $sampleForms = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    echo "\n📝 Sample SHS Forms Created:\n";
    foreach ($sampleForms as $form) {
        echo "   - {$form['clearance_form_id']}: {$form['first_name']} {$form['last_name']} ({$form['clearance_type']}, {$form['status']})\n";
    }
    
    if ($createdForms > 0) {
        echo "\n🎉 SHS clearance forms created successfully!\n";
        echo "Next step: Run signatory assignment script to link SHS signatories to these forms.\n";
    }
    
} catch (Exception $e) {
    echo "❌ Fatal Error: " . $e->getMessage() . "\n";
    exit(1);
}
?>
